# Enums
TOKEN_REGION = 'from_token'
ALBUM = 'album'
ARTIST = 'artist'
PLAYLIST = 'playlist'
TRACK = 'track'
SHOW = 'show'
EPISODE = 'episode'
REQUEST_GET = 'GET'
REQUEST_PUT = 'PUT'
REQUEST_DELETE = 'DELETE'
REQUEST_POST = 'POST'
USER = 'user'
LONG = 'long'
MEDIUM = 'medium'
SHORT = 'short'
CONTEXT = 'context'
OFF = 'off'
KEEP_PLAY_STATE = 'keep_play_state'
FORCE_PLAY = 'force_play'
PUBLIC = 'public'
PRIVATE = 'private'
PRIVATE_COLLAB = 'private_collab'

# Constants
DEFAULT_REQUEST_TIMEOUT = 10 # in seconds
