# Enums
ALBUMS = 'albums'
ARTISTS = 'artists'
PLAYLISTS = 'playlists'
TRACKS = 'tracks'
USERS = 'users'
SHOWS = 'shows'
EPISODES = 'episodes'
TOKEN_REGION = 'from_token'
REQUEST_GET = 'GET'
REQUEST_PUT = 'PUT'
REQUEST_DELETE = 'DELETE'
REQUEST_POST = 'POST'
LONG = 'long'
MEDIUM = 'medium'
SHORT = 'short'
CONTEXT = 'context'
OFF = 'off'
KEEP_PLAY_STATE = 'keep_play_state'
FORCE_PLAY = 'force_play'
PUBLIC = 'public'
PRIVATE = 'private'
PRIVATE_COLLAB = 'private_collab'
SEARCH_TYPE_ALBUM = 'album'
SEARCH_TYPE_ARTIST = 'artist'
SEARCH_TYPE_PLAYLIST = 'playlist'
SEARCH_TYPE_TRACK = 'track'
SEARCH_TYPE_SHOW = 'show'
SEARCH_TYPE_EPISODE = 'episode'

# Constants
DEFAULT_REQUEST_TIMEOUT = 10 # in seconds
SPOTIFY_PAGE_SIZE = 50
